### ISSUE TITLE
Fixing syntax errors throughout the project

### ISSUE THREAD

**Issue by AnshumaliSuri** [HackSlashNITP/Cura#1]
## Description:
There are a lot of errors in the project which halt the program from running. (Both syntax and missing code, might be due to incorrect merging of the previous PR's)

I am interested in solving this issue.
Kindly assign it to me, @RitwikSingh28

**Comment by RitwikSingh28** [comment]
This is an urgent issue. Hence, I am assigning it to you @AnshumaliSuri.

🕐 **Deadline**: 05 October 2023, 10:00 PM

**Comment by bibekpanda55** [comment]
Can work on this if it isn't resolved yet

**Comment by AnshumaliSuri** [comment]
@RitwikSingh28 
Please review the pull request 😄  .
