### ISSUE TITLE
RenderOver Flow of Post Feed Card

### ISSUE THREAD

**Issue by JayrajSinh16** [HackSlashNITP/Cura#10]
Fix the render overflow of the sub-title section of post feed card

![WhatsApp Image 2023-10-20 at 17 00 41_5deae47b](https://github.com/HackSlashNITP/Cura/assets/123794573/cb13ae48-e43d-4e30-b646-2d35e05ae05c)

**Comment by RitwikSingh28** [comment]
@JayrajSinh16 
Assigning this issue to you. 

Please let me know how you aim at removing the `pixel overflow`, so that it is fixed for all the screen devices, and not just the test device you are using.

**Comment by JayrajSinh16** [comment]
Sir In  Our case it is good reduce the fontSize of the subtitle.
In general we can  use the 'TextOverflow. ellipsis' for this Or increasing the height of the Container containing the Text Widget.
