### ISSUE TITLE
More effective UI of chat bubble

### ISSUE THREAD

**Issue by JayrajSinh16** [HackSlashNITP/Cura#11]
Need to Modify the Chat Bubble align the time and message section
and the buttom TextField

![WhatsApp Image 2023-10-20 at 17 00 41_c68a80fa](https://github.com/HackSlashNITP/Cura/assets/123794573/995b8c48-625a-4775-bccd-e50e4b8120f1)

**Comment by RitwikSingh28** [comment]
@JayrajSinh16 
Assigning this issue to you. 

Kindly brief me about the steps you aim to take in order to resolve this issue

**Comment by JayrajSinh16** [comment]
Sir here the Time info should be right align in the chat bubble, The Shape of the Chat Bubble Should be easily Distinguishable between the Sender and Receiver. And Message Should ne right align.
