### ISSUE TITLE
UI enhancement 

### ISSUE THREAD

**Issue by JayrajSinh16** [HackSlashNITP/Cura#12]
App_Bar, Submit button, Select Organization needs some UI improvement

![WhatsApp Image 2023-10-20 at 17 00 42_f6c9adce](https://github.com/HackSlashNITP/Cura/assets/123794573/7004fc98-a18b-4e52-aa5c-157883d2ac92)

**Comment by RitwikSingh28** [comment]
@JayrajSinh16 
Assigning the issue to you.
