### ISSUE TITLE
UI enhancement of the Post Card

### ISSUE THREAD

**Issue by JayrajSinh16** [HackSlashNITP/Cura#13]
Image should have some circular border
Better User Account Image
Bottom Row Icon Color

![WhatsApp Image 2023-10-20 at 17 01 56_8d49b50c](https://github.com/HackSlashNITP/Cura/assets/123794573/ceddd82b-418e-48d3-99e6-5b3c3f809911)

**Comment by RitwikSingh28** [comment]
This issue has already been resolved in a previous PR. 

Kindly re-sync your fork to see the changes.

Marking this issue as **invalid** and closing it
