### ISSUE TITLE
UI enhancement 

### ISSUE THREAD

**Issue by JayrajSinh16** [HackSlashNITP/Cura#14]
@RitwikSingh28
font Size and the search icon is not proper in the search bar
and 
there should be a clear button to clear the text in search bar instead of clearing it manually.

![WhatsApp Image 2023-10-21 at 11 10 19_649f4916](https://github.com/HackSlashNITP/Cura/assets/123794573/130ef324-4c8c-4db8-be1b-b4a3f24e9ee0)

**Comment by RitwikSingh28** [comment]
@JayrajSinh16 
Assigning this issue to you!
