### ISSUE TITLE
Visibility Problem in donation page || UI enhancement 

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Cura#4]
Sir, the container containing the entry details for donation in the donation page is not clearly visible and we have to scroll too much and it is creating problems while filling the details. kindly assign this issue to me @RitwikSingh28
![WhatsApp Image 2023-10-07 at 17 47 09_4b5752e2](https://github.com/HackSlashNITP/Cura/assets/125534462/282de10b-9ac3-4d52-8431-e98390d03d1a)

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
I assign this issue to you. This would be a quick fix, so I expect you to get this done by tonight.

**Deadline:** :clock1: 09 October, 10:00 PM

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 sir the problem has been resolved and PR has been merged
