### ISSUE TITLE
Search box not working properly in home page 

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Cura#5]
Sir, the search box is not properly implemented as the font size of text is too low and even it doesn't have any hint text. There is also a need to enhance the UI of front page as it is much light and may not be visible properly for everyone. Kindly assign this issue to me @RitwikSingh28 
![WhatsApp Image 2023-10-07 at 18 00 32_cbff7b2b](https://github.com/HackSlashNITP/Cura/assets/125534462/e41e2956-74af-49c1-93a4-5daac3a87a5f)
![WhatsApp Image 2023-10-07 at 18 00 32_a129e713](https://github.com/HackSlashNITP/Cura/assets/125534462/267533c5-73ba-4a1b-b250-dd816765f7a2)

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
Please mention the changes that you aim to make for enhancing the UI of the  `HomePage`. It would be beneficial if we discuss the proposed changes, only then the issue gets assigned to you. 

Please let me know:
* What changes you propose for better UI/UX?
* How will you implement the `search` functionality, and on what `parameters`?

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir I am going to add hintText so that UX can be enhanced and as you can see in the screenshot the font size of letters which are there in the search box is too small. Search functionality is already implemented there. If needed I would make some changes based on some keywords from the label of card itself. The main issue there is UI enhancement.

**Comment by RitwikSingh28** [comment]
Fair enough :+1: . How much time would you need to make the proposed changes @ShubhamTiwari55?

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 2 days would be enough sir
