### ISSUE TITLE
UI enhancement of posts feed page and optimising UX off the app

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Cura#8]
Sir, The posts are overlapped and some of the icons are not in proper size which makes the UI of the page bad. @RitwikSingh28 kindly assign this issue of enhancing the UI to me.
![WhatsApp Image 2023-10-12 at 00 42 36_86e76777](https://github.com/HackSlashNITP/Cura/assets/125534462/11ae57f3-6bb6-4fb8-858a-6f6060fc9b57)

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
Please let me know the UI components that you aim to fix. And also mention the time needed by you to make the changes

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir I will make the size of icons uniform, will give some margin between the posts and make the image section box rounded. 
I can complete all these changes by tomorrow 11 PM
